[workspace]
members = [
    "schnorrkel-bench",
    "schnorrkel-napi",
    "schnorrkel-neon/native",
    "schnorrkel-wasm",
    "schnorrkel-wrapper",
]

[profile.release]
lto = true
codegen-units = 1
